### PR TITLE
Documentation Bug Fix: Update ArchitectureSequenceDiagram.png

### PR DESCRIPTION
**Pull request by jetnew**
### What this does
This PR fixes a minor image inconsistency for the `ArchitectureSequenceDiagram.png`

### Notes

NA

### CODE REVIEW

**Review by JingYenLoh — COMMENTED** [review]
Sorry, where's the puml file?

**Comment by jetnew** [comment]
> Sorry, where's the puml file?

The .puml file has already previously been edited correctly, just that a new .png was not created from the .puml, therefore the .png update.

**Comment by Lysire** [comment]
Thanks for noticing this and updating the diagram to address this bug!

**Review by Lysire — APPROVED** [review]
LGTM!

**Pull request merged**
